/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_tinet_ttssc_TtsJni */

#ifndef _Included_com_tinet_ttssc_TtsJni
#define _Included_com_tinet_ttssc_TtsJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tinet_ttssc_TtsJni
 * Method:    Initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tinet_ttssc_TtsJni_Initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_tinet_ttssc_TtsJni
 * Method:    Uninitialize
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_tinet_ttssc_TtsJni_Uninitialize
  (JNIEnv *, jobject);

/*
 * Class:     com_tinet_ccic_ttssc_TtsInterface
 * Method:    request
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tinet_ttssc_TtsJni_request
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
